# Generated by Django 2.1.1 on 2018-10-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_auto_20181003_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='reps',
            field=models.CharField(default='4x 10-12 pwt', max_length=64),
        ),
    ]
