# Generated by Django 2.1.1 on 2018-10-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0005_auto_20181017_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='bar',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='parallel_bars',
            field=models.BooleanField(default='False'),
        ),
    ]
